apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        ports:
        - containerPort: 5432
