apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }} 
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
